# Maki template version: 1.0

version: '3.2'

volumes:
  db-data:


services:
  frontend:
    container_name: velo-frontend
    build:
      context: .
      dockerfile: .deploy/docker/frontend/Dockerfile
    volumes:
      - ./.deploy/docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - backend
    ports:
      - 80:80

  backend:
    container_name: velo-backend
    build:
      context: .
      dockerfile: .deploy/docker/backend/Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/app

  db:
    container_name: velo-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: velo_pass
      POSTGRES_DB: velo
      POSTGRES_USER: velo
    volumes:
      - db-data:/var/lib/postgresql/data
